spring:
  application:
    name: heynow-edge
logging:
  file: application.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
